BancAssurance.WebUI/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Multi_Insurance.WebUI.Models;

namespace Multi_Insurance.WebUI.Controllers
{
    public class InvoiceController : Controller
    {
        //
        // GET: /Invoice/
        public ActionResult GenerateInvoice()
        {
            var homeModel = (Session["ProductChosen"] as HomeViewModel);
            if (homeModel == null)
                return RedirectToAction("Index", "Home");

            ViewBag.ProductName = homeModel.Name;
            return View();
        }


        [HttpPost]
        public ActionResult GenerateInvoices()
        {
            return View();
        }

        public ActionResult GenerateCharge()
        {
            var homeModel = (Session["ProductChosen"] as HomeViewModel);
            if (homeModel == null)
                return RedirectToAction("Index", "Home");

            ViewBag.ProductName = homeModel.Name;
            return View();
        }

        [HttpPost]
        public ActionResult GenerateCharges()
        {
            return View();
        }
        
	}
}

BancAssurance.WebUI/Controllers/ProductController.cs
using System.Linq;
using System.Net.Configuration;
using System.Web.Mvc;
using Multi_Insurance.Domain.Interface;
using Multi_Insurance.WebUI.Models;

namespace Multi_Insurance.WebUI.Controllers
{
    public class ProductController : Controller
    {
        #region Instances
        private IInsuranceCompanyRepository _insuranceCompanyRepository;
        private IProductPlanRepository _productPlanRepository;
        private IMethodOfPaymentRepository _methodOfPaymentRepository;
        private IMeansOfPaymentRepository _meansOfPaymentRepository;
        private IBranchTypeRepository _branchTypeRepository;
        private IProductRepository _productRepository;
        private ProductViewModel productViewModel;
        private IProductOptionsRepository _productOptionsRepository;
        private IShelterRepository _shelterRepository;
        private IPremiumsUnderRepository _premiumsUnderRepository;
        private IRepresentativeRepository _representativeRepository;
        private ITypesIndexingRepository _typesIndexingRepository;
        private ICurrencyRatesRepository _currencyRatesRepository;
        private IAdditionalTypeInfoRepository _additionalTypeInfoRepository;
        #endregion

        #region Constructor

        public ProductController(IInsuranceCompanyRepository insuranceCompanyRepository,
                                  IProductPlanRepository productPlanRepository,
                                  IMethodOfPaymentRepository methodOfPaymentRepository,
                                  IMeansOfPaymentRepository meansOfPayment,
                                  IBranchTypeRepository branchTypeRepository,
                                  IProductRepository productRepository,
                                  IProductOptionsRepository productOptionsRepository,
                                  IShelterRepository shelterRepository,
                                  IPremiumsUnderRepository premiumsUnderRepository,
                                  IRepresentativeRepository representativeRepository,
                                  ITypesIndexingRepository typesIndexingRepository,
                                  ICurrencyRatesRepository currencyRatesRepository,
                                  IAdditionalTypeInfoRepository additionalTypeInfoRepository)
        {
            _insuranceCompanyRepository = insuranceCompanyRepository;
            _productPlanRepository = productPlanRepository;
            _methodOfPaymentRepository = methodOfPaymentRepository;
            _meansOfPaymentRepository = meansOfPayment;
            _branchTypeRepository = branchTypeRepository;
            _productRepository = productRepository;
            _productOptionsRepository = productOptionsRepository;
            _shelterRepository = shelterRepository;
            _premiumsUnderRepository = premiumsUnderRepository;
            _representativeRepository = representativeRepository;
            _typesIndexingRepository = typesIndexingRepository;
            _currencyRatesRepository = currencyRatesRepository;
            _additionalTypeInfoRepository = additionalTypeInfoRepository;
            productViewModel = new ProductViewModel();
        }

        #endregion


        public ActionResult Index()
        {
            return View(productViewModel);
        }

        #region Product Administration

        #region Company CRUD

        [HttpGet]
        public ActionResult ListOfInsuranceCompanies()
        {
            var companies = _insuranceCompanyRepository.GetInsuranceCompanies();
            return View(companies);
        }


        [HttpGet]
        public ActionResult CreateCompany()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DetailsCompany(short id)
        {
            var model = new ProductViewModel();
            var data = _insuranceCompanyRepository.GetInsuranceCompanies(id);
            foreach (var item in data)
            {
                model.InsuranceCompany = item;
            }
            return View(model);

        }


        [HttpPost]
        public ActionResult CreateCompany(ProductViewModel company)
        {
            if (!ModelState.IsValid) return PartialView(company);
            if (!Request.IsAjaxRequest()) return PartialView();

            var result = _insuranceCompanyRepository.AddCompany(company.InsuranceCompany);
            if (result == -1)
            {
                return View();
            }
            return View(company);
        }

        [HttpGet]
        public ActionResult EditCompany(short id)
        {
            var model = new ProductViewModel();
            var data = _insuranceCompanyRepository.GetInsuranceCompanies(id);
            foreach (var item in data)
            {
                model.InsuranceCompany = item;
            }
            return View(model);

        }

        [HttpPost]
        public ActionResult EditCompany(ProductViewModel company)
        {
            if (!ModelState.IsValid) return View();
            if (!Request.IsAjaxRequest()) return View();
            var result = _insuranceCompanyRepository.AddCompany(company.InsuranceCompany);
            if (result == -1)
            {
                return View();
            }
            return View(company);
        }

        [HttpDelete]
        public ActionResult EditCompany(ProductViewModel company, int id)
        {
            if (!ModelState.IsValid) return View();
            if (!Request.IsAjaxRequest()) return View();
            var result = _insuranceCompanyRepository.DeleteInsuranceCompany(company.InsuranceCompany.Id);
            if (result == -1)
            {
                return RedirectToAction("ListOfInsuranceCompanies");
            }
            return View();
        }
        #endregion

        #region Product Plans CRUD
        [HttpGet]
        public ActionResult ListOfProductPlan()
        {
            var data = _productPlanRepository.GetProductsPlan();
            return View(data);
        }

        [HttpGet]
        public ActionResult CreateProductPlan()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProductPlan(ProductViewModel productViewModelParams)
        {
            if (!ModelState.IsValid) return View(productViewModelParams);
            if (!Request.IsAjaxRequest()) return View();

            var result = _productPlanRepository.AddProductPlan(productViewModelParams.ProductPlan);
            return result == -1 ? View() : View(productViewModelParams);
        }

        [HttpGet]
        public ActionResult EditProductPlan(short id)
        {
            var model = new ProductViewModel();
            var data = _productPlanRepository.GetProductsPlanOptions(id);
            foreach (var item in data)
            {
                model.ProductPlan = item;
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult EditProductPlan(ProductViewModel productViewModelParams)
        {
            if (!ModelState.IsValid) return View(productViewModelParams);
            if (!Request.IsAjaxRequest()) return View();

            var result = _productPlanRepository.AddProductPlan(productViewModelParams.ProductPlan);
            return result == -1 ? View() : View(productViewModelParams);
        }

        [HttpDelete]
        public ActionResult EditProductPlan(ProductViewModel productViewModelParams, int ProductId)
        {
            if (!ModelState.IsValid) return View(productViewModelParams);
            if (!Request.IsAjaxRequest()) return View();

            var result = _productPlanRepository.DeleteProductPlan(productViewModelParams.ProductPlan.ProductTypeOptionId);
            if (result == -1)
            {
                RedirectToAction("ListOfProductPlan");
            }
            return View(productViewModelParams);
        }


        [HttpGet]
        public ActionResult DetailsProductPlan(short id)
        {
            var model = new ProductViewModel();
            var data = _productPlanRepository.GetProductsPlanOptions(id);
            foreach (var item in data)
            {
                model.ProductPlan = item;
            }
            return View(model);

        }
        #endregion

        #region Product Method of payment CRUD

        [HttpGet]
        public ActionResult ListOfProductMethodOfPaymentOptions()
        {
            var methodOfPayment = _methodOfPaymentRepository.GetMethodOfPaymentOptions();
            return View(methodOfPayment);
        }

        [HttpGet]
        public ActionResult CreateProductMethodOfPaymentOption()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProductMethodOfPaymentOption(ProductViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            if (!Request.IsAjaxRequest()) return View();
            var result = _methodOfPaymentRepository.AddMethodOfPaymentOption(model.MethodOfPaymentOptions);
            return result == -1 ? View() : View(model);

        }


        [HttpGet]
        public ActionResult EditProductMethodOfPaymentOption(short id)
        {
            var model = new ProductViewModel();
            var data = _methodOfPaymentRepository.GetMethodOfPaymentOptions(id.ToString());
            foreach (var item in data)
            {
                model.MethodOfPaymentOptions = item;
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult EditProductMethodOfPaymentOption(ProductViewModel model)
        {
            if (!ModelState.IsValid) return View(productViewModel);
            if (!Request.IsAjaxRequest()) return View();
            var result = _methodOfPaymentRepository.AddMethodOfPaymentOption(model.MethodOfPaymentOptions);
            return result == -1 ? View() : View(model);
        }

        [HttpDelete]

BancAssurance.WebUI/Views/Shared/BeneficiaryList.cshtml
@model Multi_Insurance.DataAccessLayer.Entities.Policy


<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Beneficiaries.FirstOrDefault().Name)</th>
            <th>@Html.DisplayNameFor(model => model.Beneficiaries.FirstOrDefault().LastName)</th>
            <th>@Html.DisplayNameFor(model => model.Beneficiaries.FirstOrDefault().IdRelationship)</th>
        </tr>
    </thead>
    <tbody>
        @{
            
            foreach (var item in Model.Beneficiaries)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                    <td>@Html.DisplayFor(modelItem => item.IdRelationship)</td>
                </tr>
            }
        }
            
        

    </tbody>
</table>

BancAssurance.WebUI/Views/Shared/CreatePolicyBeneficiary.cshtml
@model Multi_Insurance.WebUI.Models.PolicyViewModel 



@using (Ajax.BeginForm("CreatePolicy", "Policy", null,
    new AjaxOptions
    {
        HttpMethod = "post",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "beneficiaryTable"
    }
    , new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Ingrese los datos</legend>
        <div class="form-group">

            @Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().Name, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(model => model.Beneficiaries.FirstOrDefault().Name, new { @id = "beneficiaryName", @class = "form-control", @maxlenght = "50", @placeholder = "Nombre", @type = "text" })
                @Html.ValidationMessageFor(model => model.Beneficiaries.FirstOrDefault().Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().LastName, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(model => model.Beneficiaries.FirstOrDefault().LastName, new { @id = "beneficiaryLastName", @class = "form-control", @maxlength = "60", @placeholder = "Apellido", @type = "text" })
                @Html.ValidationMessageFor(model => model.Beneficiaries.FirstOrDefault().LastName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().IdRelationship, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">

                @Html.DropDownListFor(model => model.Beneficiaries.FirstOrDefault().IdRelationship, new[]
                {
                    new SelectListItem{Text = "Hijo/a", Value = "1"},
                    new SelectListItem{Text = "Tia/Tio", Value = "2"},
                }, "Selecciones", new { @id = "beneficiaryRelationship", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().Percentage, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(model => model.Beneficiaries.FirstOrDefault().Percentage, new { @id = "beneficiaryPercentage", @class = "form-control", @placeholder = "Porcentage", @type = "number" })
                @Html.ValidationMessageFor(model => model.Beneficiaries.FirstOrDefault().Percentage)
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-2">
                <button type="button" class="btn btn-primary" id="addBeneficiary">
                    Agregar Beneficiario
                </button>

                <button type="button" class="btn btn-success disabled" id="createPolicyButton">
                    Crear P&oacute;liza
                </button>
            </div>

        </div>

    </fieldset>
}


<div class="panel-default">
    <div class="panel-body">
        <div class="page-header">
            <h3 id="title" class="col-lg-offset-2">Beneficiarios </h3>
        </div>
        <div id="beneficiaryTableId" class="col-lg-offset-2 col-lg-8">
            <table id="beneficiaryTable" class="table table-striped">
                <thead>
                    <tr>
                        <th>@Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().Name)</th>
                        <th>@Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().LastName)</th>
                        <th>@Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().IdRelationship)</th>
                        <th>@Html.LabelFor(model => model.Beneficiaries.FirstOrDefault().Percentage)</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>
        </div>
    </div>
   
</div>

BancAssurance.WebUI/Views/Shared/CreateProductMeansOfPayment.cshtml
@model Multi_Insurance.WebUI.Models.ProductViewModel



@using (Ajax.BeginForm("CreateProductMeansOfPaymentOption","Product",null, 
    new AjaxOptions
    {
        HttpMethod = "post",
        OnSuccess = "onSuccessAlertMessage",
        OnFailure = "onFailureAlertMessage",
    }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Configuracion Medio de pago</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MeansOfPayment.ProductCode, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">

                @Html.DropDownListFor(m => m.MeansOfPayment.ProductCode, Model.ProductSelectListItems, 
                "Seleccione un producto",new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductSelectListItems, null, new { @class = "alert-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MeansOfPayment.MeansOfPaymenOptionCode, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">

                @Html.DropDownListFor(m => m.MeansOfPayment.MeansOfPaymenOptionCode,Model.MeansOfPaymentSelectListItems,"Seleccione un medio de pago", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MeansOfPaymentSelectListItems, null, new { @class = "alert-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-2">
                <button type="submit" class="btn btn-primary" id="productMeansOfPaymentButton">
                    Crear
                </button>
            </div>
        </div>
    </div>
}

BancAssurance.WebUI/Views/Shared/CreateProductMethodOfPayment.cshtml
@model Multi_Insurance.WebUI.Models.ProductViewModel

@using (Ajax.BeginForm("CreateProductMethodOfPayment", "Product", null,
    new AjaxOptions
    {
        HttpMethod = "post",
        OnSuccess = "onSuccessAlertMessage",
        OnFailure = "onFailureAlertMessage"
    }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Configuracion de formas de pago</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MethodOfPayment.ProductCode, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.DropDownListFor(m => m.MethodOfPayment.ProductCode, Model.ProductSelectListItems, "Seleccione un producto", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MethodOfPaymentSelectListItems, null,new {@class="alert-danger"})
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MethodOfPayment.MethodOfpaymentCode, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.DropDownListFor(m => m.MethodOfPayment.MethodOfpaymentCode, Model.MethodOfPaymentSelectListItems, "Seleccione una forma de pago", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MeansOfPaymentSelectListItems, null, new { @class = "alert-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-2">
                <button type="submit" class="btn btn-primary" id="productMethodOfPaymentButton">
                    Crear
                </button>
            </div>
        </div>
    </div>
}

BancAssurance.WebUI/Views/Shared/CreateProductOptions.cshtml
@model Multi_Insurance.WebUI.Models.ProductViewModel

@using (Ajax.BeginForm("CreateProductOptions", "Product", null,
    new AjaxOptions
    {
        HttpMethod = "post",
        OnSuccess = "onSuccessAlertMessage",
        OnFailure = "onFailureAlertMessage"
    }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Opciones del producto</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductOptions.ProductCode, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.DropDownListFor(model => model.ProductOptions.ProductCode,Model.ProductSelectListItems, "Seleccione un producto", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductSelectListItems, null, new { @class = "alert-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductOptions.PlanCode, new { @class = "col-lg-2 control-label" })
            <div class="col-lg-6">
                @Html.DropDownListFor(model => model.ProductOptions.PlanCode, Model.ProductPlanSelectItems, "Seleccione un plan", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductSelectListItems, null, new { @class = "alert-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductOptions.ValueOptions, new { @class = "col-lg-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ProductOptions.ValueOptions, new { @class = "form-control", @placeholder = "Valor de póliza", @type = "number" })
                @Html.ValidationMessageFor(model => model.ProductOptions.ValueOptions, null, new { @class = "alert-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ProductOptions.Declaration, new { @class = "col-lg-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ProductOptions.Declaration, new { @class = "form-control", @placeholder = "Declaración jurada", @type = "text", @maxlength=800 })
                @Html.ValidationMessageFor(model => model.ProductOptions.Declaration, null, new { @class = "alert-danger" })
            </div>
        </div>
        
        

        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-2">
                <button type="submit"  class="btn btn-primary"> Crear</button>
            </div>
        </div>
    </div>
}

BancAssurance.WebUI/Views/Shared/ProductPlanTable.cshtml
@model Multi_Insurance.WebUI.Models.ProductViewModel


<table class="table table-striped">
    @*
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ProductPlans.FirstOrDefault().PlanName)</th>
            <th>@Html.DisplayNameFor(model => model.ProductPlans.FirstOrDefault().AmountOption)</th>

        </tr>
    </thead>
    <tbody>
        @{

            foreach (var item in Model.ProductPlans)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.PlanName)</td>
                    <td>@Html.DisplayFor(modelItem => item.AmountOption)</td>
                </tr>
            }
        }



    </tbody>*@
</table>

BancAssurance.WebUI/Views/Shared/_BasicLayout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Multi Insurace Application">
    <meta name="author" content="do.linkedin.com/pub/fagro-vizcaino/3b/741/a24/en">
    <link rel="shortcut icon" href="~/Content/Images/favicon.ico" type="image/ico" />

    <title>@ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    @Styles.Render("~/Content/css")
    
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <![endif]-->
</head>

<body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Multiseguros", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administraci&oacute;n<b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Gestionar Compañia", "ListOfInsuranceCompanies", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Planes Productos", "ListOfProductPlan", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Formas de pago", "ListOfProductMethodOfPaymentOptions", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Medio de pago", "ListOfProductMeansOfPaymentOptions", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Ramo", "ListOfBranchTypes", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Gestores", "ListOfRepresentatives", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Indexación", "ListOfTypesIndexing", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Moneda", "ListOfCurrencyRates", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Amparo", "ListOfShelterTypes", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Info Adicional", "ListOfAdditionalTypeInfos", "Product")</li>
                            <li>@Html.ActionLink("Gestionar Productos", "ListOfProductBasicData", "Product")</li>
                        </ul>
                    </li
>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operaci&oacute;n <b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Buscar Póliza", "Search", "Policy")</li>
                            <li>@Html.ActionLink("Crear Póliza", "Create", "Policy")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Generar Pólizas Masivas", "MassivePolicyGeneration", "Policy")</li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Procesos<b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Generar Recibos", "GenerateInvoice", "Invoice")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Generar Cobros", "GenerateCharge", "Invoice")</li>
                        </ul>
                    </li>


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Herramientas<b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Diseñar producto", "CreateProduct", "Product")</li>
                            <li class="divider"></li>
                        </ul>
                    </li>


                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Productos <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Creaci&oacute;n de productos</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>*@
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Hola, @User.Identity.Name</li>
                </ul>
            </div><!--/.nav-collapse -->
        </div> <!--/container -->
    </div><!--/.navbar-->

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Multi-Insurance</p>
        </footer>
    </div><!-- /container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")

    
    
    </body>
</html>